version: '3.3'

services:

  db:
    image: postgres:15.2-alpine
    volumes:
      - ./.docker_volumes/pg_data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - 5544:5432
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready", "-d", "$(POSTGRES_DB)" ]
    #   interval: 8s
    #   timeout: 5s
    #   retries: 10
